# Generated by Django 3.0.6 on 2020-06-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
